FROM maven:3.9-eclipse-temurin-21 AS builder

WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn package -DskipTests
FROM amazoncorretto:21-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar /app/application.jar
EXPOSE 8080
ENTRYPOINT [ "java", "-jar", "/app/application.jar" ]